<a href="https://colab.research.google.com/github/raushankumar018/MLOps-Lab/blob/main/Experiment-02-Titanic-Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Cell 1: Import Libraries
import pandas as pd
import numpy as np

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline

In [2]:
# Cell 2: Upload Dataset
uploaded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset.csv

In [3]:
# Cell 3: Load Dataset
df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# Cell 4: Dataset Information
print("Shape:", df.shape)

df.info()

Shape: (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
# Cell 5: Missing Values
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
# a) Handle Missing Values
# Cell 6
# Fill Age with mean
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Fill Embarked with most frequent value
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Drop Cabin because most values are missing
df = df.drop("Cabin", axis=1)

print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [7]:
# b) Encode Categorical Variables
# Cell 7
encoder = LabelEncoder()

df["Sex"] = encoder.fit_transform(df["Sex"])

df["Embarked"] = encoder.fit_transform(df["Embarked"])

In [8]:
# c) Normalize / Scale Data

# First remove text columns.

# Cell 8
df = df.drop(["Name","Ticket"], axis=1)

df.head()

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

In [9]:
# Cell 9
X = df.drop("Survived", axis=1)

y = df["Survived"]

In [10]:
# Cell 10
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

[[-1.73010796  0.82737724  0.73769513 -0.5924806   0.43279337 -0.47367361
  -0.50244517  0.58595414]
 [-1.72622007 -1.56610693 -1.35557354  0.63878901  0.43279337 -0.47367361
   0.78684529 -1.9423032 ]
 [-1.72233219  0.82737724 -1.35557354 -0.2846632  -0.4745452  -0.47367361
  -0.48885426  0.58595414]
 [-1.71844431 -1.56610693 -1.35557354  0.40792596  0.43279337 -0.47367361
   0.42073024  0.58595414]
 [-1.71455642  0.82737724  0.73769513  0.40792596 -0.4745452  -0.47367361
  -0.48633742  0.58595414]]

In [11]:
# d) Split Dataset
# Cell 11
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(712, 8)
(179, 8)

In [12]:
# e) Automate using Pipeline
# Cell 12
pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

X_pipeline = pipeline.fit_transform(X)

print("Pipeline Applied Successfully!")

Pipeline Applied Successfully!

In [13]:
# f) Save Processed Dataset
# Cell 13
processed_df = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

processed_df["Survived"] = y.values

processed_df.to_csv(
    "Titanic_Preprocessed.csv",
    index=False
)

In [14]:
# g) Compare Before and After Preprocessing
# Cell 14
print("Original Dataset")

display(df.head())

Original Dataset

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

In [15]:
# Cell 15
print("Preprocessed Dataset")

display(processed_df.head())

Preprocessed Dataset

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survived
0,-1.730108,0.827377,0.737695,-0.592481,0.432793,-0.473674,-0.502445,0.585954,0
1,-1.726220,-1.566107,-1.355574,0.638789,0.432793,-0.473674,0.786845,-1.942303,1
2,-1.722332,0.827377,-1.355574,-0.284663,-0.474545,-0.473674,-0.488854,0.585954,1
3,-1.718444,-1.566107,-1.355574,0.407926,0.432793,-0.473674,0.420730,0.585954,1
4,-1.714556,0.827377,0.737695,0.407926,-0.474545,-0.473674,-0.486337,0.585954,0

In [16]:
# Download Processed Dataset
# Cell 16
files.download("Titanic_Preprocessed.csv")